"""added isDelete in project and task model

Revision ID: 0133799a9df3
Revises: 7cd7aa5b0fa5
Create Date: 2026-03-19 03:20:31.458632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0133799a9df3'
down_revision: Union[str, Sequence[str], None] = '7cd7aa5b0fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('isDelete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('isDelete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'isDelete')
    op.drop_column('projects', 'isDelete')
    # ### end Alembic commands ###
