"""added column status name in task table

Revision ID: 2583b7c78784
Revises: e02e846bbe99
Create Date: 2026-04-14 15:55:01.680455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '2583b7c78784'
down_revision: Union[str, Sequence[str], None] = 'e02e846bbe99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status_name', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Data migration: backfill status_name from project_statuses for rows
    # that have a status_id but no status_name yet.
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE tasks
        SET status_name = project_statuses.name
        FROM project_statuses
        WHERE tasks.status_id = project_statuses.status_id
          AND tasks.status_name IS NULL
          AND tasks.status_id IS NOT NULL
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status_name')
    # ### end Alembic commands ###
