"""changing column names

Revision ID: 4736e64c70fe
Revises: b99ab8e0fbd6
Create Date: 2026-01-03 13:15:51.726475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4736e64c70fe'
down_revision: Union[str, Sequence[str], None] = 'b99ab8e0fbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('plans', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('plans', 'UpdatedAtTimeStamp')
    op.drop_column('plans', 'CreatedAtTimeStamp')
    op.add_column('projects', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('projects', 'UpdatedAtTimeStamp')
    op.drop_column('projects', 'CreatedAtTimeStamp')
    op.add_column('subscriptions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('subscriptions', 'UpdatedAtTimeStamp')
    op.drop_column('subscriptions', 'CreatedAtTimeStamp')
    op.add_column('tasks', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('tasks', 'UpdatedAtTimeStamp')
    op.drop_column('tasks', 'CreatedAtTimeStamp')
    op.add_column('usage', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('usage', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('usage', 'UpdatedAtTimeStamp')
    op.drop_column('usage', 'CreatedAtTimeStamp')
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'UpdatedAtTimeStamp')
    op.drop_column('users', 'CreatedAtTimeStamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('usage', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('usage', 'updated_at')
    op.drop_column('usage', 'created_at')
    op.add_column('tasks', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.add_column('subscriptions', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.add_column('projects', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.add_column('plans', sa.Column('CreatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('UpdatedAtTimeStamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'created_at')
    # ### end Alembic commands ###
