"""updated projects table and task table for organization support

Revision ID: 7cd7aa5b0fa5
Revises: 39dfa3ae47a2
Create Date: 2026-03-09 23:46:03.416547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd7aa5b0fa5'
down_revision: Union[str, Sequence[str], None] = '39dfa3ae47a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'users', ['owner_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('projects', 'user_id')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_column('projects', 'organization_id')
    op.drop_column('projects', 'owner_user_id')
    # ### end Alembic commands ###
