"""updated user table and plans table

Revision ID: 7d9a45312b96
Revises: 4736e64c70fe
Create Date: 2026-01-04 00:12:35.875372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9a45312b96'
down_revision: Union[str, Sequence[str], None] = '4736e64c70fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_discontinued', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('plans', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), server_default='General', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('plans', 'is_deleted')
    op.drop_column('plans', 'is_discontinued')
    # ### end Alembic commands ###
