"""created TaskStatusHistory table

Revision ID: b48b7585cb97
Revises: 2583b7c78784
Create Date: 2026-04-14 16:38:38.968285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48b7585cb97'
down_revision: Union[str, Sequence[str], None] = '2583b7c78784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('old_status_id', sa.UUID(), nullable=True),
    sa.Column('old_status_name', sa.String(), nullable=True),
    sa.Column('new_status_id', sa.UUID(), nullable=True),
    sa.Column('new_status_name', sa.String(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_status_id'], ['project_statuses.status_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_status_id'], ['project_statuses.status_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_id'), 'task_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_history_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    # ### end Alembic commands ###
