"""add_project_statuses_task_comments_created_by_assigned_to

Revision ID: e02e846bbe99
Revises: 0133799a9df3
Create Date: 2026-04-07 23:40:01.415556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02e846bbe99'
down_revision: Union[str, Sequence[str], None] = '0133799a9df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_statuses',
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_project_statuses_status_id'), 'project_statuses', ['status_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_task_comments_comment_id'), 'task_comments', ['comment_id'], unique=False)
    op.add_column('tasks', sa.Column('status_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'project_statuses', ['status_id'], ['status_id'], ondelete='SET NULL')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'status_id')
    op.drop_index(op.f('ix_task_comments_comment_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_project_statuses_status_id'), table_name='project_statuses')
    op.drop_table('project_statuses')
    # ### end Alembic commands ###
